# Site settings
title: Big Island Extracts
email: info@bigislandextracts.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: bigislandextracts
github_username:  bigislandextracts

# Build settings
markdown: kramdown

collections:
  - services:
     output: true

copyright: Big Island Extracts

owner:
  name: Big Island Extracts
  address: 
  phone: 
  email: info@bigislandextracts.com
  company: Big Island Extracts
  site:           http://bigislandextracts.github.io
  avatar:         
  bio:            ""
  # Social networking links used in footer. Update and remove as you like.
  twitter: 
  facebook: 
  github: 
  stackexchange: 
  linkedin: 
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+'
  google_plus: 

google_analytics:

defaults:
  -
    scope: 
      path: ""
      type: posts
    values: 
      author: "Tech Rapport"
      layout: post
      path: "/blog/"
      permalink:
